version: "master-{build}"

image: Visual Studio 2019
platform:
  - x64

environment:
  winrm_user: test_user
  winrm_password: Pass@word1

  matrix:
    - ruby_version: "27"
      winrm_endpoint: http://localhost:5985/wsman
    - ruby_version: "31"
      winrm_endpoint: http://localhost:5985/wsman
    - ruby_version: "30"
      winrm_endpoint: http://localhost:5985/wsman

clone_folder: c:\projects\winrm-fs
clone_depth: 1
branches:
  only:
    - master

install:
  - ps: net user /add $env:winrm_user $env:winrm_password
  - ps: net localgroup administrators $env:winrm_user /add
  - ps: Enable-PSRemoting -Force
  - ps: winrm set winrm/config/client/auth '@{Basic="true"}'
  - ps: winrm set winrm/config/service/auth '@{Basic="true"}'
  - ps: winrm set winrm/config/service '@{AllowUnencrypted="true"}'
  - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  - ps: Write-Host $env:PATH
  - ps: ruby --version
  - ps: gem --version
  - ps: bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake integration
